import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

// Canonical site URL — override with SITE_URL env var when deploying to a real domain.
const SITE_URL = process.env.SITE_URL ?? 'https://chalachitra.example';

// Renamed-article redirects (page moves change slugs; data/redirects.json is
// regenerated by the dataset build from the pageid→slug history).
let redirects = {};
try {
  redirects = JSON.parse(readFileSync(new URL('./data/redirects.json', import.meta.url), 'utf8'));
} catch {
  /* first build / no renames yet */
}

export default defineConfig({
  site: SITE_URL,
  output: 'static',
  trailingSlash: 'never',
  redirects,
  integrations: [sitemap()],
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    inlineStylesheets: 'auto',
  },
});
